on: push

jobs:
    deploy_job:
      runs-on: ubuntu-latest
      name: deploy
      steps:
          - name: Checkout
            uses: Bhacaz/checkout-files@v2
            with: 
                files: docs
                
          - name: Deploy file
            uses: wlixcc/SFTP-Deploy-Action@v1.2.4
            with:
                username: ${{ secrets.FTP_USER}}
                server: ${{ secrets.FTP_SERVER }}
                password: ${{ secrets.FTP_PASSWORD }}
                local_path: './'
                remote_path: './'
                sftp_only: true
